# Generated by Django 4.2 on 2023-04-30 18:01

from django.db import migrations
from faker import Faker


fake = Faker()


def start(apps, schema_editor):
    Product = apps.get_model('prosucts', 'Product')
    for _ in range(1000):
        Product.objects.create(
            name=fake.word(),
            description=fake.sentence(),
            sku=fake.random.number(),
            price=fake.pydecimal(left_digits=4, right_digits=2, positive=True)
    )


def end(apps, schema_editor):
    Product = apps.get_model('prosucts', 'Product')
    Product.objects.all().delets()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            start,
            end
        )
    ]
